### ISSUE TITLE
Can't unmarshal private key to create PeerId with libp2p-crypto 0.13.0, peer-id 0.11.0

### ISSUE THREAD

**Issue by blakebyrnes** [libp2p/js-libp2p-crypto-secp256k1#7]
If you import a private key from buffer, then try to create a peer id from that, the function blows up because an extra "null" is provided to the callback.  The solution is just to avoid the extra "null" in the callback, but I couldn't figure out why that's there to begin with - possibly a previous version compatibility?

Used PeerId.createFromPrivKey
stack trace:
/Users/blakebyrnes/Projects/ulixee/toyhorse/node_modules/peer-id/src/index.js:225
        cb(err, digest, privKey)
        ^

TypeError: cb is not a function
    at privKey.public.hash (/Users/blakebyrnes/Projects/ulixee/toyhorse/node_modules/peer-id/src/index.js:225:9)
    at Multihashing.Multihashing.digest (/Users/blakebyrnes/Projects/ulixee/toyhorse/node_modules/multihashing-async/src/index.js:33:5)
    at setImmediate (/Users/blakebyrnes/Projects/ulixee/toyhorse/node_modules/multihashing-async/src/utils.js:8:7)
    at Immediate.<anonymous> (/Users/blakebyrnes/Projects/ulixee/toyhorse/node_modules/async/internal/setImmediate.js:27:16)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

**Comment by daviddias** [comment]
Looks like you are not passing a callback. 

Can you provide the full snippet of code to make this easy to reproduce?

**Comment by blakebyrnes** [comment]
Here's an example with a private key i generated for the test.
```
const crypto = require('libp2p-crypto');
const PeerId = require('peer-id');

crypto.keys.supportedKeys.secp256k1.unmarshalSecp256k1PrivateKey(Buffer.from('bcacae69e43bfbaac88ab093ba0fbf8e0281ce15833b617b81f94be64e93c687','hex'), (err, key) => {
  if (err) {
    throw err;
  }
  PeerId.createFromPrivKey(key.bytes, (err2, peerId) => {
    if (err2) {
      throw err2;
    }
  });
});
```

**Comment by daviddias** [comment]
PeerIds currently only support RSA keys. You will need to add support to other key types.

**Comment by blakebyrnes** [comment]
Am I maybe misunderstanding the point of this library then?  I assumed since it's baked into libp2p-crypto, and you can create peer ids from libp2p encoded public/private keys that this was the intent of the secp library.  

For what it's worth, I have a libp2p network up and running on these keys.  I just had to remove the second "null" sent to the callback sent to the the unmarshalSecp256k1PrivateKey function.

**Comment by blakebyrnes** [comment]
One other thing worth noting - i think this is really just an incompatibility with libp2p-crypto, where this library is included.

 **(cb) => crypto.keys.unmarshalPrivateKey(buf, cb),**
This is where this library blows up, and it's a generic function that routes to each individual type of key (ed25519, rsa, secp).

**Comment by polymeris** [comment]
Running into the exact same issue.

*EDIT*: Worked around by calling the PeerId constructor with `key.public.hash()`, `key`, and `key.public`, instead of going through `createFromPrivKey`.

**Comment by aknuds1** [comment]
I ran into the same problem and made PR #17 to rectify it.

**Comment by jacobheun** [comment]
v0.3.1 includes the patch for this.
